#!/usr/bin/env python3
"""Generate a project's tools/run_tb.py: the standalone testbench runner,
built from THIS checkout's own code -- not a copy kept in sync by hand.

The generated file bundles analog_designer/standalone/cli.py plus every
analog_designer module it imports, transitively (run_sim.py and the
standard-library-only pipeline behind it), verbatim, as `#|`-prefixed
comment lines (so the file stays plain, diffable text). Run, it unpacks
them into a temporary directory outside the project, imports cli.main()
from there and deletes the directory again -- the exact code the tool runs,
just without the tool installed:

    python -m analog_designer.standalone.export PROJECT_ROOT
    python -m analog_designer.standalone.export PROJECT_ROOT --check   # exit 1 if stale

The GUI regenerates a stale copy itself when it opens a project that has one
(see runner_status()), so a project's runner follows the tool's version.
"""
import argparse
import ast
import hashlib
import subprocess
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]  # .../analog_designer
SOURCE_ROOT = PACKAGE_ROOT.parent
ENTRY_MODULE = "analog_designer.standalone.cli"
DEFAULT_DEST = "tools/run_tb.py"
GENERATED_MARK = "# GENERATED by analog-designer-core"
_LEGACY_MARK = "# vendored from analog-designer-core"  # the first, hand-synced runner
BUNDLE_MARK = "# ==== bundled analog_designer modules (do not edit) ===="

_LAUNCHER = '''\
"""Standalone testbench runner for this project: runs its testbenches with
xschem/ngspice/Xyce on this machine (e.g. inside the EDA image), without the
analog-designer tool installed. Usage: python3 tools/run_tb.py --help

This file is generated from analog-designer-core's own simulation pipeline
(see the bundled modules below); regenerate it rather than editing it.
"""
import os
import shutil
import sys
import tempfile

BUNDLE_HASH = "{bundle_hash}"


def _unpack(dest):
    with open(os.path.abspath(__file__), encoding="utf-8") as f:
        lines = f.read().split("\\n")
    start = lines.index("{bundle_mark}")
    out = None
    for line in lines[start + 1:]:
        if line.startswith("#@ "):
            if out:
                out.close()
            path = os.path.join(dest, *line[3:].split("/"))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            out = open(path, "w", encoding="utf-8")
        elif line.startswith("#|") and out:
            out.write(line[2:] + "\\n")
    if out:
        out.close()


def _main():
    sys.dont_write_bytecode = True
    src = tempfile.mkdtemp(prefix="run_tb_src_")
    try:
        _unpack(src)
        sys.path.insert(0, src)
        from analog_designer.standalone import cli
        return cli.main()
    finally:
        shutil.rmtree(src, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(_main())
'''


#: Files bundled although nothing imports them: run_sim reads them by path
#: (run_one_openems() copies this one next to each openEMS run).
EXTRA_FILES = ("analog_designer/sim/openems_generator_runner.py",)


def _module_path(name):
    """Source file of an analog_designer module/package name, or None."""
    rel = Path(*name.split("."))
    for candidate in (SOURCE_ROOT / rel.with_suffix(".py"), SOURCE_ROOT / rel / "__init__.py"):
        if candidate.is_file():
            return candidate
    return None


def bundled_files():
    """Every analog_designer source file the entry module needs: its
    analog_designer imports, transitively (every import statement anywhere
    in a file counts, including function-level ones), plus each package's
    __init__.py. Sorted, as paths relative to SOURCE_ROOT."""
    seen, queue = set(), [ENTRY_MODULE]
    while queue:
        name = queue.pop()
        path = _module_path(name)
        if path is None or path in seen:
            continue
        seen.add(path)
        parts = name.split(".")
        for i in range(1, len(parts)):
            init = _module_path(".".join(parts[:i]))
            if init is not None:
                seen.add(init)
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if isinstance(node, ast.Import):
                queue += [a.name for a in node.names if a.name.startswith("analog_designer")]
            elif isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("analog_designer"):
                queue.append(node.module)
                queue += [f"{node.module}.{a.name}" for a in node.names]
    return sorted({p.relative_to(SOURCE_ROOT).as_posix() for p in seen} | set(EXTRA_FILES))


def bundle_hash(files=None):
    digest = hashlib.sha256()
    for rel in files or bundled_files():
        digest.update(rel.encode() + b"\0" + (SOURCE_ROOT / rel).read_bytes() + b"\0")
    return digest.hexdigest()[:16]


def _core_commit():
    result = subprocess.run(["git", "-C", str(SOURCE_ROOT), "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True)
    dirty = subprocess.run(["git", "-C", str(SOURCE_ROOT), "status", "--porcelain", "--", "analog_designer"],
                           capture_output=True, text=True)
    if result.returncode != 0:
        return "unknown"
    return result.stdout.strip() + ("+local changes" if dirty.stdout.strip() else "")


def render():
    files = bundled_files()
    digest = bundle_hash(files)
    out = [
        "#!/usr/bin/env python3",
        f"{GENERATED_MARK} {_core_commit()} (bundle {digest}) -- do not edit.",
        "# Regenerate: python -m analog_designer.standalone.export <project root>  (the GUI does it on open)",
        _LAUNCHER.format(bundle_hash=digest, bundle_mark=BUNDLE_MARK).rstrip("\n"),
        "",
        "",
        BUNDLE_MARK,
    ]
    for rel in files:
        out.append(f"#@ {rel}")
        text = (SOURCE_ROOT / rel).read_text(encoding="utf-8")
        out += [f"#|{line}" for line in text.split("\n")[:-1 if text.endswith("\n") else None]]
    return "\n".join(out) + "\n"


def _without_stamp(text):
    return "\n".join(line for line in text.split("\n") if not line.startswith(GENERATED_MARK))


def runner_status(project_root, dest=DEFAULT_DEST):
    """"missing", "current", "stale" (generated by some other core version)
    or "foreign" (a file there that this tool didn't generate -- never
    overwritten automatically)."""
    path = Path(project_root) / dest
    if not path.is_file():
        return "missing"
    text = path.read_text(encoding="utf-8")
    if GENERATED_MARK not in text and _LEGACY_MARK not in text:
        return "foreign"
    return "current" if _without_stamp(text) == _without_stamp(render()) else "stale"


def export_runner(project_root, dest=DEFAULT_DEST):
    path = Path(project_root) / dest
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")
    path.chmod(0o755)
    return path


def sync_runner(project_root, dest=DEFAULT_DEST):
    """Regenerate the project's runner if it has one and it's stale; returns
    the path written, or None. What the GUI calls on opening a project."""
    if runner_status(project_root, dest) == "stale":
        return export_runner(project_root, dest)
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("project_root")
    ap.add_argument("--dest", default=DEFAULT_DEST, help=f"path inside the project (default: {DEFAULT_DEST})")
    ap.add_argument("--check", action="store_true", help="only report whether the project's copy is current")
    args = ap.parse_args(argv)

    root = Path(args.project_root).resolve()
    if not (root / "config.json").is_file():
        sys.exit(f"no config.json in {root} -- not a project folder")
    if args.check:
        status = runner_status(root, args.dest)
        print(f"{root / args.dest}: {status}")
        return 0 if status == "current" else 1
    if runner_status(root, args.dest) == "foreign":
        sys.exit(f"{root / args.dest} exists and was not generated by this tool -- not overwriting it")
    print(f"wrote {export_runner(root, args.dest)}  ({len(bundled_files())} modules bundled)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
